[unstable]
# Enable mem feature of the compiler_builtins crate 
build-std-features = ["compiler-builtins-mem"]

# Recompile core and compiler_builtins libraries
build-std = ["core", "compiler_builtins"] 

[build]
# Override default target to avoid using --target parameter on every invocation
target = "x86_64-os_kernel.json"

[dependencies]
bootloader = "0.9"